### ISSUE TITLE
上传较大文件报错

### ISSUE THREAD

**Issue by lzdnku307** [berwin/aliyun-oss-upload-stream#11]
环境：
mac上部署，windows上访问并上传文件，使用的是项目中得例子。文件大小为50M左右，小文件倒是可以上传。
问题：报错很多：part过小或链接错误。
另外，建议：上传过程中能否只报一次错误？

**Comment by lzdnku307** [comment]
附上错误信息：
completed error!
error: { [EntityTooSmall: Your proposed upload smaller than the minimum allowed size.]
  message: 'Your proposed upload smaller than the minimum allowed size.',
  code: 'EntityTooSmall',
  headers:
   { server: 'AliyunOSS',
     date: 'Mon, 27 Jun 2016 10:09:35 GMT',
     'content-type': 'application/xml',
     'content-length': '486',
     connection: 'close',
     'x-oss-request-id': '5770FB5F1A765A446BF289F6',
     'x-oss-server-time': '227' },
  time: Mon Jun 27 2016 18:10:37 GMT+0800 (CST),
  statusCode: 400,
  retryable: false }

**Comment by berwin** [comment]
好的我看下

**Comment by jiangtao** [comment]
关注~

**Comment by berwin** [comment]
@lzdnku307 非常感谢提出bug，上周比较忙，已经修复好了，把模块更新到最新版就可以了~
