### ISSUE TITLE
上传一个7.3G的文件出现如下错误

### ISSUE THREAD

**Issue by leim** [berwin/aliyun-oss-upload-stream#16]
使用readme中的代码进行上传的，结果报错，是不是分片数量太多造成的。
error: { [InvalidArgument: Part number must be an integer between 1 and 10000, inclusive.]
  message: 'Part number must be an integer between 1 and 10000, inclusive.',
  code: 'InvalidArgument',
  headers:
   { server: 'AliyunOSS',
     date: 'Mon, 19 Sep 2016 03:09:04 GMT',
     'content-type': 'application/xml',
     'content-length': '374',
     connection: 'close',
     'x-oss-request-id': '57DF56D0D3A24AE1368F0869',
     'x-oss-server-time': '0' },
  time: Mon Sep 19 2016 11:09:04 GMT+0800 (CST),
  statusCode: 400,
  retryable: false }

**Comment by berwin** [comment]
应该是片分数量太多了，最多支持10000块分块。

**Comment by berwin** [comment]
这个问题我修一下~~

**Comment by berwin** [comment]
@leim  更新一下模块，然后使用 upload.minPartSize(5242880); 把part值调整一下，就可以解决你遇到的问题了。。如果不行就把值再调整大一些。这个值可以根据你经常上传的文件的大小自己计算一下，，就是每块part的大小。

由于前几天工作比较忙，趁着十月一修复了一下，多多担待，非常感谢您能提出问题给我
