### ISSUE TITLE
你好，我这边require了fs，但是没有这个模块

### ISSUE THREAD

**Issue by encorehe** [berwin/aliyun-oss-upload-stream#18]
我这边是使用ant design来开发一个后台应用，做到上传的时候，引用了fs模块 但是console里面log了fs.createReadStream is not fa function

有什么好的解决办法吗？

**Comment by berwin** [comment]
@encorehe  你的文件应该是从前端上传到node的吧？那其实不需要fs这个模块，我写的例子用了 fs.createReadStream 是为了模拟一个可读流~
