### ISSUE TITLE
上传大文件时出现NetworkingError: read ETIMEDOUT

### ISSUE THREAD

**Issue by csvwolf** [berwin/aliyun-oss-upload-stream#20]
Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: Error: Uncaught, unspecified "error" event. (NetworkingError: read ETIMEDOUT
 Additionally failed to abort the multipart upload on OSS: 204: null))))))))))))))))))))))))))))))))))))))))))))))))
    at Writable.emit (events.js:164:17)
    at Response.<anonymous> (/data/fe.appbuilder/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:250:12)
    at Request.<anonymous> (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:163:20)
    at Request.callListeners (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/sequential_executor.js:113:20)
    at Request.emit (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:389:14)
    at Request.transition (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:52:12)
    at AcceptorStateMachine.runTo (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:17:12)
    at /data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:66:7)
    at AcceptorStateMachine.runTo (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:17:12)
    at /data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:66:7)
    at AcceptorStateMachine.runTo (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:17:12)
    at /data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:66:7)
/data/fe.appbuilder/node_modules/aliyun-sdk/lib/request.js:99
      if (this._hardError) throw err;

**Comment by berwin** [comment]
@csvwolf 不好意思，我才看到这个issue，请问现在还有这个问题吗？
