### ISSUE TITLE
The Content-MD5 you specified was invalid

### ISSUE THREAD

**Issue by nicolasxu** [berwin/aliyun-oss-upload-stream#21]
When upload a png file, I got the following error:

message: 'The Content-MD5 you specified was invalid.',
  code: 'InvalidDigest',
  headers:
   { server: 'AliyunOSS',
     date: 'Tue, 16 Jan 2018 15:26:20 GMT',
     'content-type': 'application/xml',
     'content-length': '318',
     connection: 'close',
     'x-oss-request-id': '5A5E1990952383AD27B700B9',
     'x-oss-server-time': '46' },
  time: 2018-01-16T15:26:20.277Z,
  statusCode: 400,
  retryable: false }

**Comment by berwin** [comment]
@nicolasxu would you help me reproduce the problem?
