### ISSUE TITLE
TypeError: read.pipe is not a function

### ISSUE THREAD

**Issue by roycms** [berwin/aliyun-oss-upload-stream#22]
TypeError: read.pipe is not a function
这个是 什么 ？

**Comment by berwin** [comment]
@roycms  噢？？是你在使用的过程中报了这个错误？？

**Comment by berwin** [comment]
@roycms 您好？能帮忙发一个复现的过程吗？

**Comment by berwin** [comment]
@roycms 您好，您还在嘛？这个问题还存在嘛？如果不存在我要关闭这个issue啦~

如果您还存在这个issue可以随时回复我，我再开启这个issue
