### ISSUE TITLE
请问aliyun-oss-upload-stream如何设置代理？

### ISSUE THREAD

**Issue by haohandongku** [berwin/aliyun-oss-upload-stream#23]
大神，我现在nodejs部署在自己公司服务器内网，如何设置代理去上传图片，没有发现可以设置地方？能帮助一下吗？

**Comment by berwin** [comment]
@haohandongku 是内网无法访问`http://oss-cn-hangzhou.aliyuncs.com`这个地址嘛？🤣

**Comment by haohandongku** [comment]
是的，我这边需要代理服务器通过配置request的参数proxy的值，这样可以访问这个地址，我这样理解对吗，刚入门nodejs没多久？不明白还请见谅！

**Comment by berwin** [comment]
@haohandongku 额，，，我也没遇到过这种情况，我先研究一下 😁😁

**Comment by berwin** [comment]
@haohandongku 可能这个模块本身设置代理不是很容易、但你可以自己搭一个代理，然后把`endpoint : http://oss-cn-hangzhou.aliyuncs.com`这个地址换成代理地址，例如：`endpoint: proxy.xxx.com`然后代理地址做一个转发，转发到`http://oss-cn-hangzhou.aliyuncs.com`。

**Comment by haohandongku** [comment]
好的，试试，谢谢

**Comment by berwin** [comment]
@haohandongku  不客气~
