### ISSUE TITLE
能不能直接从客户端上传到oss

### ISSUE THREAD

**Issue by devqin** [berwin/aliyun-oss-upload-stream#7]
在做一个node cli 用的是oss 现在的上传流程是：local->server->oss;如果是基于stream去做的话，可不可以直接在server读取express的req.pipe 然后上传到服务器呢？
文章链接地址：https://devcenter.heroku.com/articles/s3-upload-node

**Comment by berwin** [comment]
#6 跟这个应该是同一个问题。。

**Comment by devqin** [comment]
@berwin 十分不好意思。看到了例子 👍
